# Generated by Django 4.2.5 on 2023-10-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Awaiting Feedback', 'Awaiting Feedback'), ('Done', 'Done')], default='Todo', max_length=20),
        ),
    ]
