# Generated by Django 4.2.5 on 2023-09-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(default='Low', on_delete=django.db.models.deletion.CASCADE, to='todo.priority'),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='subtask',
        ),
        migrations.AddField(
            model_name='todo',
            name='subtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.subtask'),
        ),
    ]
